require "gosu"

module App
  # S1 — item icon sheet (data/art/items.png, 16x16 per icon, generated by
  # tools/gen_item_icons.py, md5-pinned by data/art/items.json). Lazy Gosu
  # load (GL context law), nil-safe: a missing sheet or icon returns nil and
  # the caller draws its legacy glyph (fallback law, same as App::Art).
  class ItemIcons
    def self.load(data)
      manifest = begin
        data["art/items"]
      rescue Core::DataStore::MissingKey
        nil
      end
      manifest && new(manifest, data.root)
    end

    attr_reader :size, :md5

    def initialize(manifest, root)
      @path = File.join(root.to_s, manifest.fetch(:png))
      @size = manifest.fetch(:size, 16)
      @index = manifest.fetch(:icons).transform_keys(&:to_s)
      @md5 = manifest[:md5]
      @tiles = nil
      @failed = false
    end

    def path = @path
    def names = @index.keys.sort
    def include?(name) = @index.key?(name.to_s)

    def tiles
      return nil if @failed
      @tiles ||= begin
        Gosu::Image.load_tiles(@path, @size, @size, retro: true, tileable: false)
      rescue StandardError
        @failed = true
        nil
      end
    end

    # The Gosu::Image for an icon name (or an ItemCatalog::Item), nil if absent.
    def icon(name_or_item)
      name = name_or_item.respond_to?(:icon) ? name_or_item.icon : name_or_item.to_s
      i = @index[name]
      t = tiles
      i && t ? t[i] : nil
    end
  end
end
