require "gosu"

module App
  # PREMIUM v22 — the map stops being rectangles. A DUAL-GRID (marching
  # squares) tile layer: the visual grid is offset by half a tile, and each
  # visual cell reads the FOUR logic tiles at its corners. Per material
  # present it draws one 32x32 piece from data/art/tiles/<texture>.png —
  # the rounded blob of "where this material is" (16 corner masks x 4
  # variants, generated by tools/gen_tileset.py). Boundaries become curves,
  # lone tiles become rounded stones, inner corners get fillets; walls carry
  # a baked cliff face + cast shadow, liquids a light shallow rim.
  #
  # Pieces are NEUTRAL GREY + alpha, tinted at draw time by the zone palette
  # (Gosu color modulation), so every zone keeps its own identity from one
  # set of PNGs. Presentation only: passability, flow fields, the sim and
  # the digest never read this. Geometry is a PURE function of the zone
  # grid + registry (memoized per map); the drained bool swaps the water
  # tint at draw time. Fallback law: manifest/PNG absent -> `present?` is
  # false and the renderer keeps the flat-run path (FASE 3 faces).
  class Tileset
    Piece = Struct.new(:ref, :mask, :var)

    def self.load(data, display: {})
      manifest = begin
        data["art/tiles"]
      rescue Core::DataStore::MissingKey
        nil
      end
      return nil unless manifest && display.fetch(:tileset, true)
      new(manifest, data.root, display)
    end

    attr_reader :tile, :variants

    def initialize(manifest, root, display)
      @root = root
      @tile = manifest.fetch(:tile, 32)
      @variants = manifest.fetch(:variants, 4)
      @gain = display.fetch(:tileset_gain, 1.18).to_f
      @mats = {}
      manifest.fetch(:materials).each do |ref, spec|
        @mats[ref.to_sym] = { png: File.join(root.to_s, spec.fetch(:png)), priority: spec.fetch(:priority),
                              cls: spec.fetch(:class).to_sym, md5: spec[:md5], tiles: nil, failed: false }
      end
      @cells = {}
      @tints = {}
      # ground details (pebbles, cracks, tufts, flowers, shells): a scatter
      # over walkable non-liquid tiles, hash-placed (FNV via TileVariants.pick)
      det = manifest[:details]
      @details = det && { png: File.join(root.to_s, det.fetch(:png)), count: det.fetch(:count),
                          density: det.fetch(:density, 0.09).to_f, tiles: nil, failed: false }
      @detail_cells = {}
    end

    def materials = @mats.keys.sort
    def material?(ref) = @mats.key?(ref)
    def priority(ref) = @mats.fetch(ref)[:priority]
    def png_path(ref) = @mats.fetch(ref)[:png]
    def md5(ref) = @mats.fetch(ref)[:md5]

    # Lazy Gosu tiles per material (GL context must exist). nil -> the
    # renderer falls back for that material (draws nothing; floor fill
    # underneath keeps the frame whole).
    def tiles(ref)
      m = @mats[ref]
      return nil unless m
      return nil if m[:failed]
      m[:tiles] ||= begin
        Gosu::Image.load_tiles(m[:png], @tile, @tile, retro: true, tileable: true)
      rescue StandardError
        m[:failed] = true
        nil
      end
    end

    def image(ref, mask, var)
      t = tiles(ref)
      return nil unless t
      t[var * 16 + mask]
    end

    # --- geometry: pure function of (map, registry) --------------------------

    # The render ref of the logic tile (tx, ty), or the map's wall ref out
    # of bounds (the world ends in rock). Variants (grass_b/c) resolve
    # through TileVariants so the meadow keeps its authored patchwork.
    def ref_at(map, specs, tx, ty)
      ch = map.char_at(tx, ty)
      return oob_ref(map, specs) if ch.nil?
      spec = specs[ch]
      return oob_ref(map, specs) if spec.nil?
      if spec["passability"] == "wall"
        r = spec["render"].to_sym
        return @mats.key?(r) ? r : :wall
      end
      refs = [spec["render"]] + (spec["variants"] || [])
      r = refs[App::TileVariants.pick(map.name.to_s, tx, ty, refs.length)].to_sym
      @mats.key?(r) ? r : :floor
    end

    def oob_ref(map, _specs)
      map.palette.key?(:wall) ? :wall : :floor
    end

    # -> Array of rows; each row = Array of [px, py, base_ref, [Piece...]]
    # for visual cells (i, j) with i in 0..cols, j in 0..rows. Memoized per
    # map object (zone configs are immutable after load).
    def cells(map, registry)
      @cells[map] ||= build_cells(map, registry)
    end

    def build_cells(map, registry)
      specs = App::TileVariants.specs(map, registry)
      ts = map.tile_size
      half = ts / 2
      rows = []
      (0..map.rows).each do |j|
        row = []
        (0..map.cols).each do |i|
          corners = [ref_at(map, specs, i - 1, j - 1), ref_at(map, specs, i, j - 1),
                     ref_at(map, specs, i - 1, j), ref_at(map, specs, i, j)]
          mats = corners.uniq.sort_by { |r| [priority(r), r.to_s] }
          var = App::TileVariants.pick(map.name.to_s, i, j, @variants)
          pieces = mats.each_with_index.map do |r, k|
            mask = k.zero? ? 15 : corners.each_with_index.sum { |c, b| c == r ? (1 << b) : 0 }
            Piece.new(r, mask, var)
          end
          row << [i * ts - half, j * ts - half, pieces]
        end
        rows << row
      end
      rows
    end

    def detail_tiles
      return nil unless @details && !@details[:failed]
      @details[:tiles] ||= begin
        Gosu::Image.load_tiles(@details[:png], @tile, @tile, retro: true, tileable: false)
      rescue StandardError
        @details[:failed] = true
        nil
      end
    end

    # -> [[px, py, sprite_index, tint_ref], ...] over walkable, non-liquid,
    # non-decor tiles; ~density of them, sprite chosen by a second hash.
    def details(map, registry)
      @detail_cells[map] ||= begin
        specs = App::TileVariants.specs(map, registry)
        ts = map.tile_size
        out = []
        return out unless @details
        n = @details[:count]
        map.rows.times do |ty|
          map.cols.times do |tx|
            spec = specs[map.char_at(tx, ty)]
            next if spec.nil? || spec["passability"] == "wall"
            ref = spec["render"].to_sym
            next unless @mats.key?(ref) && @mats[ref][:cls] == :ground
            next if App::TileVariants.pick("#{map.name}:d", tx, ty, 1000) >= (@details[:density] * 1000).round
            # grass grows tufts/flowers; stone/dirt get pebbles/cracks/shells
            pool = %w[grass grass_b grass_c moss].include?(ref.to_s) ? [4, 5, 6, 4] : [0, 1, 2, 3, 7, 0]
            idx = pool[App::TileVariants.pick("#{map.name}:e", tx, ty, pool.length)]
            out << [tx * ts, ty * ts, idx, ref]
          end
        end
        out
      end
    end

    # --- draw ----------------------------------------------------------------

    def tint(map, ref)
      key = [map, ref]
      @tints[key] ||= begin
        rgb = map.palette[ref] || map.palette[:floor] || [128, 128, 128]
        r, g, b = rgb.map { |c| (c * @gain).round.clamp(0, 255) }
        Gosu::Color.new(255, r, g, b)
      end
    end

    # Draws every visual cell that intersects the camera. `drained` swaps
    # the water tint (the geometry never changes — the drained pool is the
    # same shape in another color, exactly like the flat-run path).
    # The world ends in ROCK, not in void: every visual cell the camera can
    # see is drawn — cells outside the map are solid wall (their four
    # corners are all out-of-bounds, so the full-mask wall piece), which is
    # what a pocket zone smaller than the window needs (basement_1/2 are
    # 512x448 in a 960x540 view: the void read as a broken render).
    def draw(map, registry, camera, drained: false, z: 0)
      ts = map.tile_size
      grid = cells(map, registry)
      j0 = ((camera.y - ts * 2) / ts).floor
      j1 = ((camera.y + camera.view_h + ts * 2) / ts).ceil
      i0 = ((camera.x - ts * 2) / ts).floor
      i1 = ((camera.x + camera.view_w + ts * 2) / ts).ceil
      half = ts / 2
      oob = oob_ref(map, nil)
      (j0..j1).each do |j|
        row = j.between?(0, map.rows) ? grid[j] : nil
        (i0..i1).each do |i|
          unless row && i.between?(0, map.cols)
            img = image(oob, 15, App::TileVariants.pick(map.name.to_s, i, j, @variants))
            img&.draw(i * ts - half, j * ts - half, z, 1, 1, tint(map, oob))
            next
          end
          px, py, pieces = row[i]
          pieces.each do |pc|
            img = image(pc.ref, pc.mask, pc.var)
            next unless img
            ref = pc.ref
            ref = :water_drained if drained && ref == :water && map.palette.key?(:water_drained)
            img.draw(px, py, z, 1, 1, tint(map, ref))
          end
        end
      end
      dt = detail_tiles
      return unless dt
      details(map, registry).each do |(px, py, idx, ref)|
        next if px + ts < camera.x || px > camera.x + camera.view_w ||
                py + ts < camera.y || py > camera.y + camera.view_h
        dt[idx].draw(px, py, z, 1, 1, tint(map, ref))
      end
    end
  end
end
